ARM-software/CMSIS_5

- CMSIS/DoxyGen/Pack/src/pack_check.txt
Documented the use of PackChk.exe -i to satisfy dependency checks
> SDCMSIS-425

- README.md
> CMSIS-Overview

- CMSIS/Core/Include/core_armv8mbl.h
- CMSIS/Core/Include/core_armv8mml.h
- CMSIS/DoxyGen/Core/src/Overview.txt
Increased ARMv8M SAU regions to 8.
Moved function TZ_SAU_Setup to device dependant file
partition_<device>.h.
> ARMv8M changes

- CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q15.c
corrected function header to remove doxy warnings and trimmed trailing spaces.
> removed doxy warning

- .gitignore
- CMSIS/DoxyGen/RTOS/src/cmsis_os.txt
- Moved RTX specific function documentation
- Added information on osFeature_xxx usage in RTX
> RTX documentation enhancements

- CMSIS/DoxyGen/Core/src/Ref_NVIC.txt
> Clarify NVIC virtualization use cases

- CMSIS/Core/Include/cmsis_armclang.h
- CMSIS/Core/Include/core_armv8mbl.h
- CMSIS/Core/Include/core_armv8mml.h
- CMSIS/Core/Include/core_cm3.h
- CMSIS/Core/Include/core_cm4.h
- CMSIS/Core/Include/core_cm7.h
- CMSIS/Core/Include/core_sc300.h
- CMSIS/DoxyGen/Core/src/Ref_NVIC.txt
- CMSIS/DoxyGen/Core/src/Ref_Trustzone.txt
cmsis_armclang.h:
- updated predefined macros
- reworked __TZ_*_NS functions
core_armv8m*.h:
- changed NVIC_Type, DWT_Type, CoreDebug_Type, CONTROL_Type
- reworked NVIC_*TargetState functions
core_cm*.h:
- changed CONTROL_Type
- changed macro NVIC_PRIO_BITS
> Changes according "CMSIS-Core v8M CMSIS 5.0 feedback".

- CMSIS/Core/Include/core_armv8mbl.h
- CMSIS/Core/Include/core_armv8mml.h
- CMSIS/Core/Include/core_cm4.h
- Device/ARM/ARMv8MML/Include/ARMv8MML_DP.h
- Device/ARM/ARMv8MML/Include/ARMv8MML_SP.h
- Device/ARM/ARMv8MML/Source/system_ARMv8MML.c
- Replaced ARMv8MML_FP with ARMv8MML_SP, ARMv8MML_DP.
Updated core_cm4.h.
- Removed GCC compiler warning.
Updated core_armv8m*.h.
- Corrected typo.
> Updated ARMv8MML device files.

- CMSIS/Core/Include/cmsis_gcc.h
Added inline assembly clobber descriptor for rw registry access
> Added __CMSIS_GCC_OUT_RW_REG

- CMSIS/Core/Include/cmsis_armcc.h
- CMSIS/Core/Include/cmsis_gcc.h
Small fix to silence compiler warning.
> Silenced compiler warning.

- CMSIS/Core/Include/cmsis_gcc.h
> Fix typo _WEAK -> __WEAK

- CMSIS/Core/Include/core_armv8mml.h
> Add missing return statement

- CMSIS/Core/Include/cmsis_gcc.h
The clang assembler does not know the vfpcc register, compiling
code using CMSIS will therefor fail.
This patch will use the corresponding builtin thats available on
Clang, and is supposed to be supported with GCC since Version 5.
A patch for GCC 7 is available, fixing a mistake
(https://gcc.gnu.org/ml/gcc-patches/2017-04/msg00443.html).
Optimistically this patch enabled the builtin for GCC 7.1.
> Fix __set_FPSCR and __get_FPSCR for (non-ARM) Clang

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/NN_Lib_Tests/nn_test/Ref_Implementations/arm_convolve_HWC_q15_ref_nonsquare.c
- CMSIS/NN/NN_Lib_Tests/nn_test/Ref_Implementations/ref_functions.h
- CMSIS/NN/NN_Lib_Tests/nn_test/arm_nnexamples_nn_test.cpp
- CMSIS/NN/NN_Lib_Tests/nn_test/arm_nnexamples_nn_test.uvoptx
- CMSIS/NN/NN_Lib_Tests/nn_test/arm_nnexamples_nn_test.uvprojx
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.c
> Adding convolve_HWC_q15_fast_nonsquare 

- CMSIS/RTOS2/RTX/Source/rtx_evr.c
Reverts ARM-software/CMSIS_5#410
> Revert "Fix define around EvrRtxKernelInitialized"

- CMSIS/Core/Include/cmsis_armcc.h
- CMSIS/Core/Include/cmsis_armclang.h
- CMSIS/Core/Include/cmsis_compiler.h
- CMSIS/Core/Include/cmsis_gcc.h
- CMSIS/Core/Include/cmsis_iccarm.h
- CMSIS/Core_A/Include/cmsis_armcc.h
- CMSIS/Core_A/Include/cmsis_armclang.h
- CMSIS/Core_A/Include/cmsis_compiler.h
- CMSIS/Core_A/Include/cmsis_gcc.h
- CMSIS/Core_A/Include/cmsis_iccarm.h
- CMSIS/RTOS2/RTX/Source/rtx_lib.c
Reverts ARM-software/CMSIS_5#407
> Revert "rtos: rtx5: ARMCC5: move the variables in .bss.os section to ZI section"

- CMSIS/Core_A/Include/cmsis_gcc.h
- Fixed #413 copy'n'paste error from Core to Core A
> Fixed issue #413

- CMSIS/DSP/Include/arm_math.h
- CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_init_f32.c
> Split rfft ctors

- CMSIS/DoxyGen/Core/src/Ref_SystemAndClock.txt
- Device/ARM/ARMCM0/Source/GCC/startup_ARMCM0.S
- Device/ARM/ARMCM0/Source/GCC/startup_ARMCM0.c
- Device/ARM/ARMCM0plus/Source/GCC/startup_ARMCM0plus.S
- Device/ARM/ARMCM0plus/Source/GCC/startup_ARMCM0plus.c
- Device/ARM/ARMCM1/Source/GCC/startup_ARMCM1.S
- Device/ARM/ARMCM1/Source/GCC/startup_ARMCM1.c
- Device/ARM/ARMCM23/Source/GCC/startup_ARMCM23.S
- Device/ARM/ARMCM23/Source/GCC/startup_ARMCM23.c
- Device/ARM/ARMCM3/Source/GCC/startup_ARMCM3.S
- Device/ARM/ARMCM3/Source/GCC/startup_ARMCM3.c
- Device/ARM/ARMCM33/Source/GCC/startup_ARMCM33.S
- Device/ARM/ARMCM33/Source/GCC/startup_ARMCM33.c
- Device/ARM/ARMCM35P/Source/GCC/startup_ARMCM35P.S
- Device/ARM/ARMCM35P/Source/GCC/startup_ARMCM35P.c
- Device/ARM/ARMCM4/Source/GCC/startup_ARMCM4.S
- Device/ARM/ARMCM4/Source/GCC/startup_ARMCM4.c
- Device/ARM/ARMCM7/Source/GCC/startup_ARMCM7.S
- Device/ARM/ARMCM7/Source/GCC/startup_ARMCM7.c
- Device/ARM/ARMSC000/Source/GCC/startup_ARMSC000.S
- Device/ARM/ARMSC000/Source/GCC/startup_ARMSC000.c
- Device/ARM/ARMSC300/Source/GCC/startup_ARMSC300.S
- Device/ARM/ARMSC300/Source/GCC/startup_ARMSC300.c
- Device/ARM/ARMv8MBL/Source/GCC/startup_ARMv8MBL.S
- Device/ARM/ARMv8MBL/Source/GCC/startup_ARMv8MBL.c
- Device/ARM/ARMv8MML/Source/GCC/startup_ARMv8MML.S
- Device/ARM/ARMv8MML/Source/GCC/startup_ARMv8MML.c
> Call SystemInit in the very beginning of Reset_Handler

- CMSIS/Core/Include/core_cm7.h
I noted the absence of this was noted while looking at some Mbed OS flash programming code.
I've not put in the preceding ISB that the other ICache calls have, because I don't believe it's required - either for this call or the others, but I'm not confident enough to remove the others immediately.
> Cortex-M7: Add SCB_InvalidateICache_by_Addr

- CMSIS/NN/Include/arm_nnsupportfunctions.h
For out_shift=0 the output becomes negative.
> Fix out_shift value of 31

- CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_f32.c
vmlaq_f32 proved to be a better choice for the basic dot product. The code has been tested on Cortex a5 and a53 aarch64 with the arm compiler and with gcc
> vmlaq in arm_dot_prod_f32 instead of vmulq and vadd

- CMSIS/NN/Include/arm_nnsupportfunctions.h
1. C equivalent for ARM NEON instruction VQRDMULH.
2. Rounding division by power of two.
Change-Id: Ia53d50661731bd16e88b71a4ba5df283f9977ce6
Signed-off-by: Felix Johnny <felixjohnny.thomasmathibalan@arm.com>
> Saturating doubling high multiply & divide by power of two

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_u8_basic_ver1.c
Scaling arguments follow that of a Tensorflow tflite model.
Change-Id: I9a46a2311100cc4d021ec4c671f86e8cd8acff05
> Depthwise convoltution with asymmetric quantization support.

- Device/ARM/ARMCM7/Source/startup_ARMCM7.c
changed: 
startup_ARMCM4.c
to:
startup_ARMCM7.c
> Fixed filename typo on line 2

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_add_q7.c
Convolution function is for TFLu support.Support function for matrix
multiplication is added as well.
> CMSIS-NN: New function for s8 convolution using symmetric quantization

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c
This is a reference version and optimized version will follow.
> CMSIS-NN : Added function for s8 depthwise convolution

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ActivationFunctions/arm_nn_activations_q15.c
- CMSIS/NN/Source/ActivationFunctions/arm_nn_activations_q7.c
- CMSIS/NN/Source/ActivationFunctions/arm_relu_q15.c
- CMSIS/NN/Source/ActivationFunctions/arm_relu_q7.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15_reordered.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_accumulate_q7_to_q15.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_add_q7.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mult_q15.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mult_q7.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_no_shift.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_no_shift.c
- CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
- CMSIS/NN/Source/PoolingFunctions/arm_pool_q7_HWC.c
- CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_q15.c
- CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_q7.c
- CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_with_batch_q7.c
All but those related to arm_nn_elementwise_add_s8.c are fixed.
> CMSIS-NN: Fix Doxygen warnings

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16_reordered.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_accumulate_q7_to_q15.c
- CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
Removed doxygen style comment above function definition so
the header file is the sole reference.
Additional comments for Fully Connected and Average pool.
> CMSIS-NN: Comment and doxygen updates

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c
Element wise multiplication of two vectors.
Supported framework: TensorFlow Lite micro
> CMSIS-NN : int8 element wise multiplication

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ActivationFunctions/arm_relu_q15.c
- CMSIS/NN/Source/ActivationFunctions/arm_relu_q7.c
General code cleanup. No new or change in functionality.
> CMSIS_NN: Update read/write macros for relu q7/q15

- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
Removed traling spaces and unified naming for input arguments.
> CMSIS-NN: Fix typecast error in Fully connected s8

- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/README.md
List of functions that support s8 TFL specifiction is added along
with information like the additional memory that is required.
History is updated.
> CMSIS-NN : Added a table of s8 functions for quick reference.

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8_opt.c
This patch is dependent on the non-DSP max pool function.
> CMSIS-NN : Add DSP optimzied s8 max pool function

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ActivationFunctions/arm_relu6_s8.c
Pure C implementation applicable for all M cores.
Change-Id: I387eb79cca376f82ab82a212122dbf62895e5b5b
> CMSIS-NN : Added relu6 function

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8.c
Pure C max pool function for s8.
> CMSIS-NN : s8 max pool basic function

- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c
M-Profile Vector Extension support is added along
with a vector function for requantization.
> CMSIS-NN : MVE support for elementwise add

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16_reordered.c
Added constraint on output channel and simplified the loops.
> CMSIS_NN: Update 1x1 conv for s8

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_u8.c
- Added new function for supporting Softmax layer Uint8
- Tweaked the Softmax layer Int8 implementation
- The implementation is bit accurate with TFLu
> CMSIS-NN: Implement bit accurate function for Softmax layer - Uint8

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
M-Porfile Vector Extension support is added.
Author: christophe0606
> CMSIS-NN: MVE support for s8 Fully connected and MatMul

- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c
1. M-Profile Vector Extension is added for core loop of convolution.
2. Tail handling is either pure C or with DSP extension.
> CMSIS-NN: MVE support for s8 conv

- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/README.md
Change-Id: I838ddb450d94ac17a90eb4ea05d79498cde91e3c
> CMSIS-NN: Update API Index  and history

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8.c
- CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8_opt.c
Updated copyright year in header files
> CMSIS-NN: MVE support for max pool

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/ReshapeFunctions/arm_reshape_s8.c
1. ARM_MATH_MVEI is explained.
2. Link to TensorFlow is provided
3. Doxygen warning fixes
> CMSIS-NN: Documentation update

- CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c
- CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
1. Made arm_avgpool_s8_get_buffer_size visible to MVE
2. Renamed arm_mve_sat_doubling_high_mult to arm_sat_doubling_high_mult_mve
> CMSIS-NN: average_pool and element_add bug fix

- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_with_offset.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c
Updated the revision and date for the following files:
- arm_q7_to_q15_reordered_with_offset.c
- arm_q7_to_q15_with_offset.c
- arm_nn_supportfunctions.h
- arm_convolve_1x1_s8_fast.c
> CMSIS-NN: Updated revision and date

- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_1x_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_4x_s8.c
Performance of 1x1 conv is improved for Multi Vector Extension.
Added two new files:
1. arm_nn_mat_mul_core_1x_s8.c
2. arm_nn_mat_mul_core_4x_s8.c
> CMSIS-NN: Improve performance of 1x1 conv for MVE

- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c
Incorrect update of kernel pointers is fixed.
> CMSIS-NN: Fix incorrect index usage in  conv for MVE

- CMSIS/DSP/Include/arm_math.h
- CMSIS/DSP/Source/BasicMathFunctions/arm_and_u16.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_and_u32.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_and_u8.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_not_u16.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_not_u32.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_not_u8.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_or_u16.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_or_u32.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_or_u8.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u16.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u32.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u8.c
- CMSIS/DSP/Testing/FrameworkInclude/Error.h
- CMSIS/DSP/Testing/FrameworkSource/Error.cpp
- CMSIS/DSP/Testing/Include/Tests/BasicTestsQ15.h
- CMSIS/DSP/Testing/Include/Tests/BasicTestsQ31.h
- CMSIS/DSP/Testing/Include/Tests/BasicTestsQ7.h
- CMSIS/DSP/Testing/Source/Tests/BasicTestsQ15.cpp
- CMSIS/DSP/Testing/Source/Tests/BasicTestsQ31.cpp
- CMSIS/DSP/Testing/Source/Tests/BasicTestsQ7.cpp
- CMSIS/DSP/Testing/desc.txt
- Added MVE support for logical operators
- Modified prototypes (q15 -> u16, etc...)
- Adapted test framework for unsigned integers
> CMSIS-DSP: Added MVE support for logical operators (modified prototypes)

- CMSIS/NN/Include/arm_nnfunctions.h
Range of input offset is corrected from int8 to -127 to 128
> CMSIS-NN: Update comment on input offset

- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
The new implementation does not require temporary buffers
> CMSIS-NN: Optimized fully connected layer for Cortex-M4/M7

- CMSIS/DSP/Include/arm_math.h
- CMSIS/DSP/Source/SupportFunctions/arm_spline_interp_f32.c
- CMSIS/DSP/Source/SupportFunctions/arm_spline_interp_init_f32.c
- CMSIS/DSP/Testing/Include/Tests/SupportTestsF32.h
- CMSIS/DSP/Testing/Source/Tests/SupportTestsF32.cpp
- CMSIS/DSP/Testing/desc.txt
- Moved coefficients computation to init function
- Improved documentation
> CMSIS-DSP: Modified spline f32 to compute coeffs at init time

- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c
Further opttimization is done for the regular convolution case
for Multi-Vector Extention case.
> CMSIS-NN: Improve performance of convolution for MVE

- CMSIS/NN/README.md
Information is added on the key differences between the APIs that
support TFL micro and the legacy APIs
> CMSIS-NN: Add information on legacy and TFL micro compliant APIs

- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c
revert non-supported intrinsics for ARMC6.14
> CMSIS-NN: Revert *_x/1_* intrinsics for MVE

- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/README.md
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_padded_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_s8.c
Performance(cycles) of the generic depthwise convolution is improved. Following
new functions are added.
1. arm_nn_depthwise_conv_nt_t_s8()
2. arm_nn_depthwise_conv_nt_t_padded_s8()
> CMSIS-NN: Improve performance of depthwise conv for MVE

- ARM.CMSIS.pdsc
- CMSIS/DoxyGen/NN/src/history.txt
1. All CMSIS-NN soure files are listed in ARM.CMSIS.pdsc
2. Version history is updated
> CMSIS-NN List source files and update revision number

- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_padded_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
> CMSIS-NN Doxygen formatting fixes

- CMSIS/Core/Include/core_armv81mml.h
- CMSIS/Core/Include/core_cm55.h
- CMSIS/Core/Include/pmu_armv8.h
Updated core_armv81mml.h and pmu_armv8.h.
New PMU functions, macros and register struct.
> Updated pmu_armv8.h with PMU functions and macro definitions.

- CMSIS/Core/Include/pmu_armv8.h
Aligned PMU function prototypes and definitions for PMU counter overflow status and PMU interrupt enable/disable functions.
Also fixed spacing issue with some comments.
> Aligned PMU function prototypes and definitions

- CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_s8.c
- CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_u8.c
Tail predication is added where possible.
Conditional execution instead of generic execution of code.
> CMSIS-NN Improve performance of softmax for MVE

- CMSIS/NN/Include/arm_nnfunctions.h
Update CMSIS-NN documentation about the upcoming CMSIS-NN interface change
> Update CMSIS-NN documentation

- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
Loop that enables tail predication is added and moved
to arm_nn_vec_mat_mult_t_s8.c.
> CMSIS-NN: Tail Predicate Loops in Fully Connected operator

- CMSIS/NN/Include/arm_nn_types.h
> CMSIS-NN: CMSIS-NN structs for the TensorFlowLite micro compliant functions

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_u8_basic_ver1.c
1. Bit exactness error is fixed and performance is improved.
2. Constraints on the input dimensions are removed.
> CMSIS-NN: Fix and improve performance of depthwise conv u8

- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_convolve_1x1_s8_fast/test_arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_convolve_s8/Unity/unity_test_arm_convolve_s8.c
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_convolve_s8/test_arm_convolve_s8.c
The API's are updated to reflect the modified interface.
> CMSIS-NN: Update unit test for convolution as per new interface

- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/Include/arm_nn_types.h
- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s8.c
1. The DW conv functions are updated as per the new interface
using structs.
2. New wrapper file/function arm_depthwise_conv_wrapper_s8 is added
> CMSIS-NN: Update DW conv to new interface

- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/Include/arm_nn_types.h
- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s8.c
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_3x3_s8/Unity/unity_test_arm_depthwise_conv_3x3_s8.c
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_3x3_s8/test_arm_depthwise_conv_3x3_s8.c
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8/test_arm_depthwise_conv_s8.c
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8_opt/test_arm_depthwise_conv_s8_opt.c
Unit tests for DW conv are updated as per new interface
using structs. Two new test cases are added as well.
> CMSIS-NN: Update DW conv unit tests to new interface

- CMSIS/NN/Include/arm_nn_types.h
- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
- CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
1. arm_avgpool_s8() is updated to use the new interface.
2. arm_fully_connected_s8() is updated to the new interface.
> CMSIS-NN: Update average pool and fully conncted to new interface

- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c
The optmization takes into consideration
the ranges of arguments for requantization.
This affects almost all convolution,
depthwise convolution, fully connected APIs
> CMSIS-NN : Optimize requantization

- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/Include/arm_nn_types.h
- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/README.md
- CMSIS/NN/Source/SVDFunctions/arm_svdf_s8.c
Optimized version of the SVDF-kernel compatible with TensorFlow Lite Micro.
> Add implementation of SVDF kernel.

- CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
1. Sum is done over 32 bits instead of the existing
16 bits for Cortex-M CPUs with DSP extension.
2. Variable names are re-named to be uniform with
max pool.
> CMSIS-NN: Sum over 32 bits for Average pool

- ARM.CMSIS.pdsc
- Device/ARM/ARMCM0/Source/GCC/gcc_arm.ld
- Device/ARM/ARMCM0/Source/GCC/startup_ARMCM0.S
- Device/ARM/ARMCM0plus/Source/GCC/gcc_arm.ld
- Device/ARM/ARMCM0plus/Source/GCC/startup_ARMCM0plus.S
- Device/ARM/ARMCM1/Source/GCC/gcc_arm.ld
- Device/ARM/ARMCM1/Source/GCC/startup_ARMCM1.S
- Device/ARM/ARMCM23/Source/GCC/gcc_arm.ld
- Device/ARM/ARMCM23/Source/GCC/startup_ARMCM23.S
- Device/ARM/ARMCM3/Source/GCC/gcc_arm.ld
- Device/ARM/ARMCM3/Source/GCC/startup_ARMCM3.S
- Device/ARM/ARMCM33/Source/GCC/gcc_arm.ld
- Device/ARM/ARMCM33/Source/GCC/startup_ARMCM33.S
- Device/ARM/ARMCM35P/Source/GCC/gcc_arm.ld
- Device/ARM/ARMCM35P/Source/GCC/startup_ARMCM35P.S
- Device/ARM/ARMCM4/Source/GCC/gcc_arm.ld
- Device/ARM/ARMCM4/Source/GCC/startup_ARMCM4.S
- Device/ARM/ARMCM55/Source/GCC/gcc_arm.ld
- Device/ARM/ARMCM7/Source/GCC/gcc_arm.ld
- Device/ARM/ARMCM7/Source/GCC/startup_ARMCM7.S
- Device/ARM/ARMSC000/Source/GCC/gcc_arm.ld
- Device/ARM/ARMSC000/Source/GCC/startup_ARMSC000.S
- Device/ARM/ARMSC300/Source/GCC/gcc_arm.ld
- Device/ARM/ARMSC300/Source/GCC/startup_ARMSC300.S
- Device/ARM/ARMv81MML/Source/GCC/gcc_arm.ld
- Device/ARM/ARMv8MBL/Source/GCC/gcc_arm.ld
- Device/ARM/ARMv8MBL/Source/GCC/startup_ARMv8MBL.S
- Device/ARM/ARMv8MML/Source/GCC/gcc_arm.ld
- Device/ARM/ARMv8MML/Source/GCC/startup_ARMv8MML.S
Fixing GCC data/bss handling. This should resolve #632.
> Aligned GCC linker description and assembler startup with C startup.

- CMSIS/NN/Tests/UnitTest/generate_test_data.py
Change quantization during generation of output reference data.
Change-Id: I6694324b42499763cf654d3a47ecb05962cac6d8
> CMSIS-NN: Fix fully connected unit test

- CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
Change-Id: Iddbfa81cd8457e72225730ac2e42d3217b8f90ab
> CMSIS-NN: Improve MVE performance of FC operator

- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c
Applicable for non-DSP extension use case.
Change-Id: I1c5b39d96f86ef1c79421be48d76845295c9b78a
> CMSIS-NN: Optimize loop termination for 1x1 conv

- CMSIS/NN/Include/arm_nn_tables.h
- CMSIS/NN/Include/arm_nn_types.h
- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
clang format files in the NN/include folder
> CMSIS-NN: clang format include files

- ARM.CMSIS.pdsc
- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/Include/arm_nnfunctions.h
1. ARM.CMSIS.pdsc file updated with recent file changes
2. Updated revision history and version number
3. arm_nnfunctions.h file is clang formatted
> CMSIS-NN: Update revision history

- CMSIS/NN/Tests/UnitTest/unittest_targets.py
Parses generated test runners in the unit tests.
> CMSIS-NN: Fix warning: redundant redeclaration

- CMSIS/NN/.clang-format
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ActivationFunctions/arm_relu_q15.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_accumulate_q7_to_q15.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_no_shift.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_with_offset.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c
* Adding arm_nn_write_q15x2_ia replacing write_q15x2_ia in CMSIS-DSP.
* Updating clang format to not have brace wrapping after extern.
> CMSIS-NN: Add arm_nn_write_q15x2_ia

- CMSIS/NN/Tests/UnitTest/CMakeLists.txt
- CMSIS/NN/Tests/UnitTest/Corstone-300/linker.ld
- CMSIS/NN/Tests/UnitTest/Corstone-300/linker.scatter
- CMSIS/NN/Tests/UnitTest/Corstone-300/retarget.c
- CMSIS/NN/Tests/UnitTest/Corstone-300/uart.c
- CMSIS/NN/Tests/UnitTest/Corstone-300/uart.h
- CMSIS/NN/Tests/UnitTest/README.md
Copying linker files and uart code from Arm
Ethos-U Core Platform project.
Updating CMake and README.
> CMSIS-NN: Make unit test more independent

- ARM.CMSIS.pdsc
- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/README.md
1. Revision hisory is updated to reflect the interface change
2. Support link is added
> CMSIS-NN: Update revision number & support info

- CMSIS/Core/Include/cmsis_armcc.h
- CMSIS/Core/Include/cmsis_armclang.h
- CMSIS/Core/Include/cmsis_armclang_ltm.h
- CMSIS/Core/Include/cmsis_gcc.h
- CMSIS/Core/Include/cmsis_iccarm.h
- CMSIS/CoreValidation/Source/CV_CoreSimd.c
- CMSIS/DoxyGen/Core/src/Ref_cm4_simd.txt
Targetted optimization for GCC when  __SXTAB
is used with __ROR.
> CMSIS-Core : Add support for __SXTAB16_RORn

- ARM.CMSIS.pdsc
- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/Include/arm_nn_types.h
- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
Fully Connected implementation is updated to reflect
zero weight offset as per int8 spec.
MVE version and non-DSP extension versions are updated
> CMSIS-NN : Update weight offset as zero in FC

- ARM.CMSIS.pdsc
- CMSIS/Core/Include/cmsis_iccarm.h
- CMSIS/DSP/Projects/IAR/arm_cortexM_math.ewp
- CMSIS/RTOS2/RTX/Source/rtx_lib.c
- Device/ARM/ARMCM23/Source/IAR/startup_ARMCM23.s
- Device/ARM/ARMCM33/Source/IAR/startup_ARMCM33.s
- Device/ARM/ARMCM35P/Source/IAR/startup_ARMCM35P.s
Forgot to add cmsis_iccarm.h updated with stack sealing support.
> Build: Update to IAR 5.8.0 update

- ARM.CMSIS.pdsc
- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/CMakeLists.txt
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_svdf_s8.c
- CMSIS/NN/Source/SVDFunctions/arm_svdf_s8.c
1. MVE specific optimization added for SVDF
2. NULL bias support is added for SVDF
> CMSIS-NN : MVE support for SVDF

- CMSIS/DoxyGen/Driver/src/Driver_SPI.c
> CMSIS-Driver: minor update in SPI documentation

- CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/inc/jtest_test.h
- CMSIS/DSP/DSP_Lib_TestSuite/parseLog.py
- CMSIS/DSP/DSP_Lib_TestSuite/parseLog_SV.py
- CMSIS/DSP/Include/arm_math_types.h
- CMSIS/DSP/Include/dsp/svm_functions.h
- CMSIS/DSP/Include/dsp/svm_functions_f16.h
- CMSIS/DSP/Platforms/IPSS/ARMCR5/system_ARMCR5.c
- CMSIS/DSP/Platforms/IPSS/ARMCR52/system_ARMCR52.c
- CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q15.c
- CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_f16.c
- CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_f32.c
- CMSIS/DSP/Testing/FrameworkInclude/ArrayMemory.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_HWC_q7_fast_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_u8_basic_ver1.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c
- CMSIS/RTOS2/RTX/Examples/TrustZoneV8M/RTOS_Faults/CM33_s/IncidentLog_s.h
I'd modify mispelling words to its correct words.
> fix word typo

- CMSIS/Core/Include/core_cm55.h
CM55 Power Mode Control Registers structure definition added
> [CMSIS Core] Added CM55 Power Mode Control Registers definition

- .gitignore
- Jenkinsfile
- docker/dockerfile
- docker/getDependencies.sh
- docker/requirements.txt
- docker/rtebuild/armcc.rtebuild
- docker/rtebuild/armclang.rtebuild
- docker/rtebuild/armclang_ltm.rtebuild
- docker/rtebuild/gcc.rtebuild
- docker/rtebuild/toolchain.rtebuild
- Dockerfile with getDependencies.sh
- Pipeline stages for Docker lint, build and promote
> Docker: Add dockerfile for Linux build environment.

- CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
Performance improvement for processors with DSP extension
to negate changes from adding NULL bias support.
Minor degradation is seen for Coretex-M4 and GCC combination.
Change-Id: Id49e8f52ea71b4573cd0288051ae1004485fd64e
> CMSIS-NN: ARMC6 Performance improvement for FC kernel

- CMSIS/Core/Include/cmsis_armcc.h
- CMSIS/Core/Include/cmsis_armclang.h
- CMSIS/Core/Include/cmsis_armclang_ltm.h
- CMSIS/Core/Include/cmsis_gcc.h
PR solving request from Edmund Player raised in dsg-cmsis.
> CMSIS-Core(M): added instruction barrier (ISB) to set_CONTROL functions.

- CMSIS/Utilities/gen_pack.sh
- Generate pack outside of a Git repository.
- Flag to ignore pack check errors.
- Flag to overwrite pack version.
> Utilities: Enhanced gen_pack to be more resilient.

- CMSIS/NN/Tests/UnitTest/requirements.txt
Versions of urllib3 & tensorflow are updated
> CMSIS-NN: Update versions of packages in requirements.txt

- .github/workflows/fileheader.sh
- .github/workflows/fileheader.yml
- CMSIS/Utilities/check_header.sh
The check_header.sh script checks a given file for changes
made to its file header, i.e. @date and @version. For each
file that did not receive a proper update a warning message
is generated.
> GitHub: Add action to check file headers.

- CMSIS/NN/CMakeLists.txt
- CMSIS/NN/README.md
- CMSIS/NN/Source/ActivationFunctions/CMakeLists.txt
- CMSIS/NN/Source/BasicMathFunctions/CMakeLists.txt
- CMSIS/NN/Source/CMakeLists.txt
- CMSIS/NN/Source/ConcatenationFunctions/CMakeLists.txt
- CMSIS/NN/Source/ConvolutionFunctions/CMakeLists.txt
- CMSIS/NN/Source/FullyConnectedFunctions/CMakeLists.txt
- CMSIS/NN/Source/NNSupportFunctions/CMakeLists.txt
- CMSIS/NN/Source/PoolingFunctions/CMakeLists.txt
- CMSIS/NN/Source/ReshapeFunctions/CMakeLists.txt
- CMSIS/NN/Source/SVDFunctions/CMakeLists.txt
- CMSIS/NN/Source/SoftmaxFunctions/CMakeLists.txt
- CMSIS/NN/Tests/UnitTest/CMakeLists.txt
- CMSIS/NN/Tests/UnitTest/README.md
This is fix for: https://github.com/ARM-software/CMSIS_5/issues/1206
> CMSIS-NN: Build CMSIS-NN as a library

- CMSIS/DoxyGen/Driver/src/Driver_USART.c
Here are some minor corrections and changes in the USART driver documentation.
Please review and merge into the main CMSIS repo.
> CMSIS-Driver: minor update of USART documentation

- CMSIS/Utilities/check_header.sh
Blaming the file version didn't work, properly.
Relates to #1323
> Utilities: Fix check_header script

- CMSIS/RTOS2/RTX/Library/IAR/IDE/RTX_CM.ewp
- CMSIS/RTOS2/RTX/Library/IAR/IDE/RTX_CM.eww
This adds support for M55 with EWARM 9.20.1
> RTX: Add IAR support for v8.1

- CMSIS/DSP/Platforms/FVP/ARMCM0/Include/system_ARMCM0.h
- CMSIS/DSP/Platforms/FVP/ARMCM0/LinkScripts/IAR/lnk.icf
- CMSIS/DSP/Platforms/FVP/ARMCM0/LinkScripts/IAR/mem_ARMCM0.h
- CMSIS/DSP/Platforms/FVP/ARMCM0/Startup/IAR/startup_ARMCM0.c
- CMSIS/DSP/Platforms/FVP/ARMCM0/system_ARMCM0.c
- CMSIS/DSP/Platforms/FVP/ARMCM33/Include/system_ARMCM33.h
- CMSIS/DSP/Platforms/FVP/ARMCM33/LinkScripts/IAR/lnk.icf
- CMSIS/DSP/Platforms/FVP/ARMCM33/LinkScripts/IAR/mem_ARMCM33.h
- CMSIS/DSP/Platforms/FVP/ARMCM33/Startup/IAR/startup_ARMCM33.c
- CMSIS/DSP/Platforms/FVP/ARMCM33/system_ARMCM33.c
- CMSIS/DSP/Platforms/FVP/ARMCM4/LinkScripts/IAR/lnk.icf
- CMSIS/DSP/Platforms/FVP/ARMCM4/LinkScripts/IAR/mem_ARMCM4.h
- CMSIS/DSP/Platforms/FVP/ARMCM4/Startup/IAR/startup_ARMCM4.c
- CMSIS/DSP/Platforms/FVP/ARMCM4/system_ARMCM4.c
- CMSIS/DSP/Platforms/FVP/ARMCM7/Include/system_ARMCM7.h
- CMSIS/DSP/Platforms/FVP/ARMCM7/LinkScripts/IAR/lnk.icf
- CMSIS/DSP/Platforms/FVP/ARMCM7/LinkScripts/IAR/mem_ARMCM7.h
- CMSIS/DSP/Platforms/FVP/ARMCM7/Startup/IAR/startup_ARMCM7.c
- CMSIS/DSP/Platforms/FVP/ARMCM7/system_ARMCM7.c
- CMSIS/DSP/Platforms/FVP/ARMv81MML/Include/system_ARMv81MML.h
- CMSIS/DSP/Platforms/FVP/ARMv81MML/LinkScripts/IAR/lnk.icf
- CMSIS/DSP/Platforms/FVP/ARMv81MML/LinkScripts/IAR/mem_ARMv81MML.h
- CMSIS/DSP/Platforms/FVP/ARMv81MML/Startup/IAR/startup_ARMv81MML.c
- CMSIS/DSP/Platforms/FVP/ARMv81MML/system_ARMv81MML.c
- CMSIS/DSP/Toolchain/ICCARM.cmake
- CMSIS/DSP/Toolchain/Tools.cmake
- CMSIS/DSP/iccarm.cmake
> DSP: Add IAR tool chain

- CMSIS/NN/Examples/README.md
- CMSIS/NN/README.md
Authors: oscarandersson8218, Sebastian-Larsson (GitHub)
Functions added:
- arm_convolve_wrapper_s16
- arm_convolve_s16
- arm_convolve_fast_s16
- arm_convolve_1_x_n_s8 (previously arm_convolve_1_n_s8)
- arm_depthwise_conv_wrapper_s8
- arm_fully_connected_s16
Adding link to example project.
> CMSIS-NN: Updating API documentation & adding examples directory

- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c
Conditionalize dilation code path in depthwise_conv_s8_generic.
> CMSIS-NN: Update depthwise_conv_s8_generic

- CMSIS/NN/Include/arm_nnsupportfunctions.h
Adapt to Tflite/TfliteMicro, which will use single rounding instead of double rounding:
https://github.com/tensorflow/tensorflow/pull/50290
Changes are added under flag CMSIS_NN_USE_SINGLE_ROUNDING, which is
disabled by default.
> CMSIS-NN: Use single rounding

- CMSIS/NN/Tests/UnitTest/requirements.txt
https://github.com/advisories/GHSA-57wx-m983-2f88
> tensorflow version including security patch

- CMSIS/DoxyGen/Driver/src/Driver_WiFi.c
- CMSIS/Driver/Include/Driver_WiFi.h
- Activate function
- Socket Create function
- Socket Receive/RecvFrom/Send/SendTo function (support for polling)
> CMSIS-Driver WiFi: Update documentation

- CMSIS/DAP/Firmware/Source/DAP.c
The clock delay calculation code is refactored into `Set_DAP_Clock_Delay()`, which is called from both `DAP_Setup()` and
`DAP_SWJ_Clock()`.
This change allows the default clock frequency to use fast clock mode. It was required for the micro:bit v2 firmware.
cc @gerargz @mbrossard @microbit-carlos
> DAP: refactor clock delay calculation

- ARM.CMSIS.pdsc
- CMSIS/Core/Include/core_cm85.h
- CMSIS/Core/Include/pac_armv81.h
- CMSIS/DoxyGen/SVD/src/svd.txt
- CMSIS/DoxyGen/SVD/src/svd_schema.txt
- CMSIS/DoxyGen/SVD/svd.dxy
- CMSIS/Utilities/CMSIS-SVD.xsd
- Device/ARM/ARMCM85/Include/ARMCM85.h
- Device/ARM/ARMCM85/Include/Template/partition_ARMCM85.h
- Device/ARM/ARMCM85/Include/system_ARMCM85.h
- Device/ARM/ARMCM85/Source/ARM/ARMCM85_ac6.sct
- Device/ARM/ARMCM85/Source/ARM/ARMCM85_ac6_s.sct
- Device/ARM/ARMCM85/Source/GCC/gcc_arm.ld
- Device/ARM/ARMCM85/Source/startup_ARMCM85.c
- Device/ARM/ARMCM85/Source/system_ARMCM85.c
- Device/ARM/SVD/ARMCM85.svd
- Add generic ARMCM85 device
- Add Cortex-M85 (CM85) to SVD schema
> CMSIS-Core(M): Add Cortex-M85 support

- CMSIS/NN/Source/SVDFunctions/arm_svdf_s8.c
- CMSIS/NN/Source/SVDFunctions/arm_svdf_state_s16_s8.c
Fix bug in SVDF function with ARM_MATH_DSP define
Fix for: #1472
> CMSIS-NN: Correct SVDF bug for ARM_MATH_DSP #1472
