ARM-software/CMSIS_5

- Device/_Template_Vendor/Vendor/Device/Source/IAR/startup_Device.s
For IAR Embedded Workbench for ARM version 7.10.1 and later the assembly files generated with the vendor template give a warning. Visit https://www.iar.com/support/tech-notes/assembler/warning25-label-xxxxx-is-defined-pubweak-in-a-section-implicitly-declared-root/ for details.
Fixed template as described in IAR tech-note.
> Added :NOROOT to avoid warning in .s files created with vendor template

- CMSIS/DoxyGen/Pack/src/config_wizard.txt
Changed the documentation to make the user better understand what he can do with <c> and <!c> in Configuration Wizard
> Clarification on the usage of <c> and <!c> in the Configuration Wizard

- CMSIS/DoxyGen/Doxygen_Templates/printComponentTabs.js
remove section RTX from CMSIS documentation because it is not yet available.
> remove section RTX from CMSIS documentation

- CMSIS/Core/Include/cmsis_gcc.h
We compile with these warnings enabled and -Werror so we hit this pretty quickly.
> Suppressing warning for unaligned int.

- CMSIS/Core/Include/core_cm3.h
- CMSIS/Core/Include/core_cm4.h
To make the use of the CMSIS_NVIC_VIRTUAL feature easier, include a header file with a standard name. This header file will be provided by the client of the CMSIS_NVIC_VIRTUAL feature to define which implementations of the NVIC functions should be used.
Also, additionally allow the virtualization NVIC_SystemReset.
@RobertRostohar
> Improve NVIC virtualization mechanism

- CMSIS/RTOS2/RTX/Source/GCC/irq_armv8mbl.S
- CMSIS/RTOS2/RTX/Source/GCC/irq_armv8mbl_ns.S
- CMSIS/RTOS2/RTX/Source/GCC/irq_armv8mml.S
- CMSIS/RTOS2/RTX/Source/GCC/irq_armv8mml_fp.S
- CMSIS/RTOS2/RTX/Source/GCC/irq_armv8mml_fp_ns.S
- CMSIS/RTOS2/RTX/Source/GCC/irq_armv8mml_ns.S
- CMSIS/RTOS2/RTX/Source/GCC/irq_cm0.S
- CMSIS/RTOS2/RTX/Source/GCC/irq_cm3.S
- CMSIS/RTOS2/RTX/Source/GCC/irq_cm4f.S
The GCC ASM files were renamed from *.s to *.S. However, the names by
which these files are referenced were not completely updated. This leads
to problems on case sensitive file systems.
Update the name by which the GCC ASM files are referenced, so as not to
break the build on case sensitive file systems.
Fixes: 9f7ce666db32 "RTX: renamed GCC ASM files extension (*.s to *.S)"
@RobertRostohar
> RTX: Fix GCC ASM .file and .include for *.S

- CMSIS/RTOS2/RTX/Source/rtx_thread.c
terminate_list is supposed to be a double linked list. At least osRtxThreadListUnlink() expects one. The thread->prev pointer of already terminated threads were kept to nullptr, building a sinle linked list. The function osRtxThreadListUnlink() may corrupt the terminate_list when join() or detach() is called in a different order than the threads that terminated before.
> Bugfix: terminate_list may be corrupted upon join() or detach()

- CMSIS/Core/Include/core_armv8mbl.h
- CMSIS/Core/Include/core_armv8mml.h
- CMSIS/Core/Include/core_cm0.h
- CMSIS/Core/Include/core_cm0plus.h
- CMSIS/Core/Include/core_cm23.h
- CMSIS/Core/Include/core_cm33.h
- CMSIS/Core/Include/core_cm7.h
- CMSIS/Core/Include/core_sc000.h
- CMSIS/Core/Include/core_sc300.h
Previously, we only included "cmsis_vectab_virtual.h" and "cmsis_nvic_virtual.h" on some cores. Now, we allow this on all cores.
Previously, we didn't support virtualizing NVIC_SystemReset on all cores. Now, we do support virtualizing NVIC_SystemReset on all cores.
> Improve the NVIC virtualization features on all cores

- CMSIS/Core/Include/cmsis_armclang.h
- CMSIS/Core/Include/cmsis_gcc.h
- CMSIS/DoxyGen/Core/src/Ref_Trustzone.txt
Currently missing from v8-M, presumable because there is no msr/mrs for SP for v7-M cos that would be redundant.
You may want to implement this for this for the other compilers too, I'm currently not set up to test that, sorry.
cc @JonatanAntoni
> Add __TZ_get/set_SP for v8-M

- CMSIS/RTOS2/RTX/Source/core_cm.h
The GCC version of the function 'atomic_link_put' compares two identical values. This compare always matches, which causes race conditions when using 'osRtxMemoryPoolAlloc' in the interrupt context.
> Fixed bug in GCC version of function atomic_link_put

- CMSIS/Core/Include/cmsis_compiler.h
- CMSIS/RTOS2/RTX/Library/IAR/IDE/RTX_CM.ewp
``__CORE__`` is IAR specific, similar to ``__ARM_ARCH_`` macros that GCC defines. Plus I removed those macros from ewp file.
reference: #149 
Note: I am working on different code base where I was testing this patch, please test it or let me know how I could test this within this code base (run any local tests). I tried to open .eww project but as in the reference, I probably have newer IAR version thus the project is not compatible.
> cmsis: fix IAR architecture macros

- CMSIS/Core/Include/cmsis_armcc.h
- CMSIS/Core/Include/cmsis_armclang.h
- CMSIS/Core/Include/cmsis_compiler.h
- CMSIS/Core/Include/cmsis_gcc.h
Hi,
Has discussed in ticket #203, this is a proposal to have a macro which handle pack union attribute to work with different compilers.
I have checked with armclang 6.6, armcc 5.06 update 4 and gcc 5.4.0
> CMSIS-Core: #203 compiler macro for packed union

- CMSIS/Core/Include/core_armv8mml.h
- CMSIS/Core/Include/core_cm33.h
- CMSIS/Core/Include/core_cm7.h
While reviewing the SCB structure against the Cortex M7 User guide I just stumbled over a small copy & paste error in the comments for the MVFR2 register. 
http://infocenter.arm.com/help/topic/com.arm.doc.dui0646b/DUI0646B_cortex_m7_dgug.pdf
> Fix wrong comment in SCB about MVFR2 register

- CMSIS/Core/Include/cmsis_gcc.h
My last pull request had some optimisitc version check, the fix was not included in gcc 7.1.
This PR adjusts the version to 7.2, as the gcc-7 branch has the fix included [1], and the next release will be based on that
[1] - https://github.com/gcc-mirror/gcc/commits/gcc-7-branch/gcc/config/arm/arm-builtins.c
> Correct gcc version check for __builtin_arm_[gs]et_fpscr builtins

- CMSIS/Core/Include/cmsis_iccarm.h
Updated a few unsigned integer literals to use "U" instead of "u" in CMSIS_5/CMSIS/Core/Include/cmsis_iccarm.h
> Replaced a few "u" with "U"

- CMSIS/RTOS2/RTX/Source/ARM/irq_armv8mbl.s
- CMSIS/RTOS2/RTX/Source/GCC/irq_armv8mbl.S
- CMSIS/RTOS2/RTX/Source/IAR/irq_armv8mbl_common.s
Switch to secure/nonsecure context save/restore is based on 6th bit in LR register, correct the bug (R7 instead of LR was used for decision)
Issue: https://github.com/ARM-software/CMSIS_5/issues/257
> Systick handler switch to secure/nonsecure

- CMSIS/Core_A/Include/core_ca.h
I added the macro definition for non-cache area.
> CMSIS-Core(A): Add MMU section_normal_nc macro

- CMSIS/Core/Include/cmsis_gcc.h
This prevents multiple warnings when compiling with GCC
```
ext/cmsis/cmsis_gcc.h:1539:6: warning: "__ARM_FEATURE_DSP" is not defined, evaluates to 0 [-Wundef]
#if (__ARM_FEATURE_DSP == 1)                             /* ToDo ARMCLANG: This should be ARCH >= ARMv7-M + SIMD */
^~~~~~~~~~~~~~~~~
```
I also fixed the same issue for ICC.
@JonatanAntoni: I believe the `ToDo` does not apply anymore, since you now have a separate header for armclang anyways. I took the liberty of removing it, is that correct?
> Core(M): Fix -Wundef for __ARM_FEATURE_DSP

- CMSIS/RTOS2/Source/os_tick_ptim.c
That is to enabled integration with build-it-all Mbed OS type build system.
@JonatanAntoni
> Move non-config includes behind PTIM ifdef

- CMSIS/Core/Include/cmsis_armclang.h
- CMSIS/Core/Include/cmsis_gcc.h
- CMSIS/Core/Include/core_cm7.h
In C++17 `register` keyword was removed. Current gcc 8.1.0 produces
following warning if `-std=c++17` flag is used:
warning: ISO C++17 does not allow 'register' storage class specifier
[-Wregister]
GCC almost completely ignores `register` keyword, with rare exception of
`-O0` when additional copy from/to stack may be generated.
For simplicity of the codebase it is better to just remove this
problematic keyword where it is not strictly required.
See: http://en.cppreference.com/w/cpp/language/storage_duration
Closes issue #345
> Remove `register` keyword from public headers

- CMSIS/RTOS2/RTX/Include/rtx_evr.h
Comes from https://github.com/ARMmbed/mbed-os/pull/7355. Thanks to @deepikabhavnani for finding.
@JonatanAntoni @RobertRostohar Please review
> events: fix semicolon for event timer macros

- CMSIS/RTOS2/RTX/Source/rtx_evr.c
Rename the define EVR_RTX_KERNEL_INITIALIZE_COMPLETED_DISABLE to
EVR_RTX_KERNEL_INITIALIZED_DISABLE so it matches the reset of the
codebase.
The commit 858f429461e04921644f41eca9d7b63248434bd2 -
"RTX5: minor change in events (name consistency)" initially
changed this define but missed this one spot.
> Fix define around EvrRtxKernelInitialized

- CMSIS/DoxyGen/Core/src/Ref_Debug.txt
Didn't find any reference to 'Serial Viewer Output' on any ARM page. Therefore I assume that the correct expression is 'Serial Wire Output'.
> Changed 'Serial Viewer Output' to 'Serial Wire Output'

- CMSIS/DoxyGen/Core/src/Ref_Debug.txt
Reverts ARM-software/CMSIS_5#412
> Revert "Changed 'Serial Viewer Output' to 'Serial Wire Output'"

- CMSIS/Core/Include/cmsis_armcc.h
- CMSIS/Core/Include/cmsis_armclang.h
- CMSIS/Core/Include/cmsis_compiler.h
- CMSIS/Core/Include/cmsis_gcc.h
- CMSIS/Core/Include/cmsis_iccarm.h
- CMSIS/Core_A/Include/cmsis_armcc.h
- CMSIS/Core_A/Include/cmsis_armclang.h
- CMSIS/Core_A/Include/cmsis_compiler.h
- CMSIS/Core_A/Include/cmsis_gcc.h
- CMSIS/Core_A/Include/cmsis_iccarm.h
- CMSIS/RTOS2/RTX/Source/rtx_lib.c
The thread stacks and other large variables in rtx_lib.c were directed
to .bss.os section, which puts them to zero initialized section in GCC,
but on ARMC5 they were put to data section which consumes precious ROM.
In reality the data section compression may make this a NOP change,
but it will at least make the total result statistics now more reliable.
Effects of this PR on the output of mbed compile of one application:
```
--8<--8<--
> --- memory_before_bss_change.txt	2018-06-18 16:45:51.928844313 +0300
> +++ memory_after_bss_change.txt	2018-06-18 16:57:27.753532437 +0300
> @@ -5,6 +5,9 @@
>  +----------------------------------------------------------+--------+-------+-------+
>  | Module                                                   |  .text | .data |  .bss |
> …
```
> rtos: rtx5: ARMCC5: move the variables in .bss.os section to ZI section

- CMSIS/Core_A/Include/core_ca.h
Fixed a bug that compilation fails if core_ca.h is included twice.
> CMSIS-Core(A): Fixed the position of "extern "C""

- CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f64.c
While using the DSP library in a project compiled with gcc and the `-Werror` setting I've  hit a number of `-Werror=double-promotion` instances in `arm_mat_inverse_f64.c`
This is triggered by comparing a wide float values with literals declared with the f suffix, eg `0.0f`
This patch resolves the issue by using the long float suffix instead.
For reference, this is the compiler error seen before this patch:
```
cmsis/CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f64.c: In function 'arm_mat_inverse_f64':
cmsis/CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f64.c:211:16: error: implicit conversion from 'float' to 'float64_t {aka double}' to match other operand of binary expression [-Werror=double-promotion]
if (maxC == 0.0f)
^~ …
```
> DSP: fix double-promotion warnings in arm_mat_inverse_f64

- CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.c
In algorithm's stage2, the base address of px should depend on the value of firstIndex and srcBLen.
refer to https://github.com/ARM-software/CMSIS_5/issues/165
> DSP: fix arm_conv_paratial* bugs.

- CMSIS/Core/Include/core_cm3.h
The ACTLR register itself is conditional on chip revision, but its bit definitions were always defined.
Make the the bit definitions also conditional, so it is possible to produce portable code that sets DISDEFWBUF if available:
#ifdef SCnSCB_ACTLR_DISDEFWBUF_Msk
SCnSCB->ACTLR |= SCnSCB_ACTLR_DISDEFWBUF_Msk;
#endif
> CM3: Make ACTLR bit definitions conditional

- CMSIS/RTOS2/RTX/Source/ARM/irq_ca.s
- CMSIS/RTOS2/RTX/Source/GCC/irq_ca.S
- CMSIS/RTOS2/RTX/Source/IAR/irq_ca.s
Safe use of LDREX/STREX requires that any thread switches, interrupts or
any other disruption between the LDREX and STREX be visible, so
exception handlers must ensure that the exclusive monitor flag is clear
when returning to foreground code.
Two possible error cases are
~~~~
<thread 1>
LDREX          exclusive monitor set
<thread switch 2>
STR            exclusive monitor cleared
LDREX          exclusive monitor set
<thread switch 1>
STREX          !!! store succeeds because exclusive monitor set
~~~~
or
~~~~
<thread>
LDREX          exclusive monitor set
<IRQ>
STR            exclusive monitor cleared
LDREX          exclusive monitor set
// No store because of failed compare-and-swap
<IRQ return>
STREX          !!! store succeeds because exclusive monitor set
~~~~
For ARMv7-M and …
> RTX5: Add CLREX to exception exit paths

- CMSIS/NN/Include/arm_nnsupportfunctions.h
Input of zero gives bad output due to overflow.
> Fixing shift on zero issue

- CMSIS/RTOS2/RTX/Source/rtx_thread.c
By inspection, this will have the following effects:
* A second call to osThreadJoin while the first is still waiting will now
return with osErrorResource, rather than starting a join on this thread
and leaving the first thread to never wake - we trap and avoid this
application-caused deadlock.
* A call to osThreadDetach while an osThreadJoin is still waiting will
now return with osErrorResource; this previously would have cleared
the joinable flag and returned osOK.
* svcRtxThreadExit and svcRtxThreadTerminate implementations can be
slightly simplified, as they only need to check the Joinable flag to
decide whether to immediately free.
> RTX5: Have osThreadJoin mark thread non-joinable

- CMSIS/Core/Include/cmsis_armcc.h
- CMSIS/Core/Include/cmsis_armclang.h
- CMSIS/Core/Include/cmsis_armclang_ltm.h
- CMSIS/Core/Include/cmsis_compiler.h
- CMSIS/Core/Include/cmsis_gcc.h
- CMSIS/Core/Include/cmsis_iccarm.h
- CMSIS/Core/Include/core_armv8mbl.h
- CMSIS/Core/Include/core_armv8mml.h
- CMSIS/Core/Include/core_cm0.h
- CMSIS/Core/Include/core_cm0plus.h
- CMSIS/Core/Include/core_cm1.h
- CMSIS/Core/Include/core_cm23.h
- CMSIS/Core/Include/core_cm3.h
- CMSIS/Core/Include/core_cm33.h
- CMSIS/Core/Include/core_cm35p.h
- CMSIS/Core/Include/core_cm4.h
- CMSIS/Core/Include/core_cm7.h
- CMSIS/Core/Include/core_sc000.h
- CMSIS/Core/Include/core_sc300.h
- CMSIS/Core_A/Include/cmsis_armcc.h
- CMSIS/Core_A/Include/cmsis_armclang.h
- CMSIS/Core_A/Include/cmsis_compiler.h
- CMSIS/Core_A/Include/cmsis_gcc.h
- CMSIS/Core_A/Include/cmsis_iccarm.h
__NVIC_DisableIRQ and __NVIC_EnableIRQ can be used to function as a mutex-style protection lock against a particular interrupt handler, similar to __disable_irq and __enable_irq for all interrupts.
However, __NVIC_EnableIRQ, unlike a mutex unlock or __enable_irq, had no compiler barriers. Being just a volatile write, in the following code sequence:
NVIC_DisableIRQ(devx);
// modify some RAM accessed by devx IRQ handler
NVIC_EnableIRQ(devx);
there would be nothing preventing the RAM accesses from moved below the NVIC_EnableIRQ.
Add barriers to NVIC_EnableIRQ, so that the above code works the same as a mutex or __disable_irq, without any added need to mark the shared RAM as volatile.
Fixes issue #493
> __NVIC_EnableIRQ compiler barriers 

- CMSIS/DSP/Source/CommonTables/arm_common_tables.c
Rectified error on formula that generates Twiddle coefficients table for RFFT (line 17749)
> Rectified Description error on twiddeCoeff_rfft_32

- CMSIS/NN/Source/PoolingFunctions/arm_pool_q7_HWC.c
Handle the case in max pooling when the number of channels is not multiple of 4.
See the description of #511.
Fix #511.
> Fix issue #511.

- CMSIS/NN/Include/arm_nn_tables.h
Fixed duplicated declaration of `sigmoidHTable_q15`, `sigmoidLTable_q15`.
@felix-johnny as you suggested I moved the contribution to `develop` (#543)
Alessandro
> `arm_nn_tables.h`: removed duplicated declaration

- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_u8_basic_ver1.c
In arm_depthwise_conv_u8_basic_ver1.c added end of
group(Doxygen) for file.
> Fix Doxygen warning

- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_no_shift.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c
1. Added function arm_q7_to_q15_with_offset.c
2. Replaced __SIMD32 macros in arm_q7_to_q15_no_shift.c
as an improvement.
> CMSIS-NN: Add function for q7 to q15 conversion with offset

- CMSIS/NN/Include/arm_nnsupportfunctions.h
Using parentheses in macros is a good way to avoid problems.
> parentheses in macros

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c
Update to remove range checks from inner loop of generic  depthwise
conv s8 implementation.
> CMSIS-NN : Move out 'if' checks from inner loop of depthwise conv

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c
1. Added new function for s8 depthwise conv supporting TensorFlow
micro framework.
2. Fixed incorrect comment in
arm_depthwise_separable_conv_HWC_q7_nonsquare.
> CMSIS_NN: Optimized s8 depthwise conv for channel multiplier = 1

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16_reordered.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_with_offset.c
A simplified int8 version of the generic convolution for the
1x1 convolution case.
Supported framework: TensorFlow Lite micro
> CMSIS-NN: s8 1x1 convolution

- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ActivationFunctions/arm_relu_q15.c
- CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_HWC_q7_fast_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_basic.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_mat_q7_vec_q15.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_mat_q7_vec_q15_opt.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q15.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q15_opt.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
- CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
- CMSIS/NN/Source/PoolingFunctions/arm_pool_q7_HWC.c
In the process the following bugs are fixed.
1. Incorrect index  calculation in inner loop of depthwise conv s8.
2. output offset was unused in mul s8.
> CMSIS_NN : Fix compiler warnings for Wall and Wextra

- CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.c
The same vld1q_f32 was computed at the beginning and at the end of a do-while loop. I removed the one at the end (in the disassembly it was already ignored by the compiler)
> Removed useless vld1q_f32 from arm_correlate_f32

- CMSIS/DSP/Include/arm_math.h
- CMSIS/DSP/PythonWrapper/setup.py
This fixes the build issues, re enabling the pywrapper for the DSP library on linux
> CMSIS-DSP enable building python wrapper files for gnu linux

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
- CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
Adding interface to get required buffer size for the operators that need it.
> CMSIS-NN: Get optimized implementation temporary buffer sizes

- ARM.CMSIS.pdsc
- CMSIS/RTOS2/RTX/Config/RTX_Config.h
`OS_THREAD_LIBSPACE_NUM` is defined to 4, which is not a good default in all cases. This change makes it possible to give `OS_THREAD_LIBSPACE_NUM` also as a (compiler) macro.
> Change OS_THREAD_LIBSPACE_NUM to be defined as a (compiler) macro

- CMSIS/DSP/README.md
Fix 'cross compil' to 'cross compile' in `CMSIS/DSP/README.md`
> Fix CMSIS-DSP README.md spell error

- CMSIS/RTOS2/RTX/Source/rtx_core_cm.h
The file `rtx_core_cm.h` defines `TRUE` and `FALSE` macros. This change protects these definitions in case they are already defined. This can happen if the MCU's CMSIS register definition header defines such macros, which will included through the `#include CMSIS_device_header` line.
A much better fix would be to use the `true` and `false` definitions from `<stdbool.h>`, which is already included in this header. There is no need to define your custom bool types, especially since they are just redefined to the same as the ones in `<stdbool.h>`. If you'll accept such a proper fix, I'll make the changes.
> Protect TRUE/FALSE defines for RTOS2

- CMSIS/DAP/Firmware/Include/DAP.h
Due to a bug in gcc when compiling for v6-M, it is necessary to explicitly switch to unified syntax. The compiler automatically inserts a `.syntax divided` directive just before the inline asm, and returns to unified syntax afterwards.
Without this patch, you'll get an error like this…
Error: instruction not supported in Thumb16 mode -- `subs r7,r7,#1'
when compiling for M0 or M0+.
See [gcc bug 15348](https://sourceware.org/bugzilla/show_bug.cgi?id=15348). There are also multiple forum topics online where people ran into the same issue with inline asm based delay routines.
It was also necessary to change the operand constraint for delay from `r` to `l` so that only low registers are selected.
> Fix issues with inline asm version of PIN_DELAY_SLOW() for v6-M

- CMSIS/DSP/Include/arm_helium_utils.h
We don't need to load them with an mve intrinsic, but instead can
just pass them in where needed.
> [MVE] clean-up of loading constant offset vectors

- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_depthwise_conv_s8_core.c
Fix names that  were missed in the renaming of
arm_mve_requantize_32x4 to arm_requantize_mve_32x4.
> CMSIS-NN: Fix arm_mve_requantize_32x4 renaming

- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c
1. Fix out of bounds access.
2. Fix lane for addition of kernels.
> CMSIS-NN: 1x1 conv bug fixes for MVE

- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_with_offset.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c
The issue was related to the offset casted to int8_t rather than int16_t.
In case of int8_t offset, we could not handle properly the cases with negative offset.
In particular, the creation of the vector variable offset_q15x2 was not correct
since we did not extend the sign bit
Signed-off-by: Gian Marco Iodice <gianmarco.iodice@arm.com>
> CMSIS-NN: Fixed bug in arm_q7_to_q15_with_offset

- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
The **input_x** is unused just as the **input_y** when in **ARM_MATH_LOOPUNROLL** and **ARM_MATH_DSP** mode
> fixed unused variable error for arm_convolve_s8_1x1_fast

- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q7.c
Casting using **void*** gives a compiler error (on _arm-none-eabi-g++_), as it discards the **const qualifier**.
**void*** cast is not needed since **read_and_pad_reordered**'s first parameter is **const q7_t***
Also, **read_and_pad_reordered** returns **const q7_t***, so the **q7_t*** cast is not needed since variable **pB** is already **const q7_t***.
> Removed unnecessary casts

- CMSIS/DSP/Include/arm_math.h
- CMSIS/DSP/PrivateInclude/arm_sorting.h
- CMSIS/DSP/Source/SupportFunctions/arm_merge_sort_f32.c
- CMSIS/DSP/Source/SupportFunctions/arm_merge_sort_init_f32.c
- CMSIS/DSP/Source/SupportFunctions/arm_sort_f32.c
- CMSIS/DSP/Source/SupportFunctions/arm_spline_interp_f32.c
- CMSIS/DSP/Source/SupportFunctions/arm_spline_interp_init_f32.c
- CMSIS/DSP/Testing/Include/Tests/SupportTestsF32.h
- CMSIS/DSP/Testing/Source/Tests/SupportTestsF32.cpp
- Added working buffer for spline interpolation f32 that must be allocated by the user
- Added working buffer for merge sort f32 (and removed function from arm_sort_f32 since the instance has different fields) that must be allocated by the user
> CMSIS-DSP: Corrected issues 773 and 774

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16_reordered.c
Constraint on output channel to be a multiple of 2 is removed
from arm_convolve_1x1_s8_fast() API
> CMSIS-NN: remove output channel constraint on 1x1 conv

- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/README.md
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_1x_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_4x_s8.c
1. MVE specific function for 1xN convolution.
2. Updated use of macro ARM_MATH_AUTOVECTORIZE
3. Updated history for new function that is added.
> CMSIS-NN: 1xN conv support for MVE

- CMSIS/DSP/Source/SupportFunctions/arm_quick_sort_f32.c
- CMSIS/DSP/Testing/desc.txt
Added function that return a computed pivot as soon as in the array there is not anything remaining to swap. In this way the computed value can be used to create correctly the sub-arrays and avoid infinite recursion in the case of a constant signal.
Improved documentation too.
> CMSIS-DSP: Improved arm_quick_sort_f32

- CMSIS/NN/Include/arm_nnfunctions.h
Description of missing kernel_x argument is added as doxygen
comment.
> CMSIS-NN: Update API comment for arm_convolve_1_x_n_s8

- CMSIS/DoxyGen/NN/src/history.txt
- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/README.md
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c
The new function:
- is used to accelerate the 1x1 convolution layer
- does not require temporary buffers
- does not have any limitations on the input dimensions
> CMSIS-NN: Optimized matrix multiplication function for Cortex-M7

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ActivationFunctions/arm_relu_q15.c
- CMSIS/NN/Source/ActivationFunctions/arm_relu_q7.c
- CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c
- CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16_reordered.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_no_shift.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_with_offset.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c
- CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
- CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8_opt.c
- CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_q7.c
This macro must be supplied via build system, which might be hard for an end user to know, hence creating a non-optimal user experience.
> CMSIS-NN/DSP: Remove ARM_MATH_LOOPUNROLL

- ARM.CMSIS.pdsc
- Device/ARM/ARMSC000/Include/ARMSC000.h
- Device/ARM/ARMSC300/Include/ARMSC300.h
core_sc300.h should be included instead of core_SC300.h
> Device: SC300: Fix wrong SC300 core header file inclusion

- CMSIS/NN/Include/arm_nnsupportfunctions.h
CMSIS macro __RESTRICT is used to enable compiling with
C++ modes as well.
> CMSIS-NN: Use __RESTRICT instead of restrict keyword

- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_with_offset.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c
SXTAB substitutes SXTB and SADD combination. This change affects
Cortex-M cores with DSP extension(E.g Cortex-M4 and Cortex-M7)
> CMSIS-NN: Use SXTAB instead of SXTB and SADD16 for DSP extension

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/README.md
- CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
The existing optimization(partial x and y) for DSP extension
is found not to be bit exact. As a first step, the optimization
is removed and will be replaced by a new optimization in the second
step.
> CMSIS_NN: Remove DSP extension optimization for avg pool

- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c
The new _x intrinsic is not availble for vdup in ARMC6.14. Reverting
back to the old one.
> CMSIS-NN: revert intrinsics for vdup(MVE)

- CMSIS/NN/Include/arm_nnfunctions.h
Added arm_convolve_1_x_n_s8_get_buffer_size() to interface.
Re-arranged location of arm_convolve_1x1_s8_fast_get_buffer_size
> CMSIS-NN: Add missing API to interface

- CMSIS/Core/Include/cmsis_iccarm.h
- CMSIS/Core_A/Include/cmsis_iccarm.h
Small fix to add SPDX id to 2 files that we found during the scan in core files.
> core: add SPDX identifier

- ARM.CMSIS.pdsc
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c
1. MVE support is added to depthwise_conv_s8_mult_4() for requantization.
2. CMSIS version is bumped up in ARM.CMSIS.pdsc
> CMSIS-NN Add MVE support in requantization for a variant of DWC

- Device/ARM/ARMCM55/Include/ARMCM55.h
Changing from 12 to 8 to align with Cortex-M55's default number when the PMU is configured.
> Updating PMU Event Counter Number

- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
The ouptut pointer is updated for batch greater than 1 for
Fully Connected operator. The fix is applicable for all Cortex-M CPUs
except for Cortex-M55.
> CMSIS-NN: Fix for batch greater than  1 case  in Fully Connected

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_s8.c
Applies to arm_softmax_s8().
1. Data type of diff min in input argument is changed to int32 from
int8.
2. For non-MVE versions, the data type of  variable holding the
difference with the max element in row is corrected from int8 to
int32.
> CMSIS-NN: Fix incorrect data type in Softmax (Interface change)

- CMSIS/NN/Source/ActivationFunctions/arm_nn_activations_q15.c
Avoid returning 0 for negative values  and fix
the linear interpolation step when a value has no right upper bound.
See the discussion in #470.
This fixes #470.
> Fix bug #470 (Bug related to arm_nn_activations_direct_q15)

- CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FilteringFunctions/biquad.c
Added apparently missing "const" to ref_biquad_cascade_df2T_f64(), which
was causing compile errors with IAR toolchain.
> CMSIS-DSP: Added missing "const"

- CMSIS/Core/Include/core_armv81mml.h
- CMSIS/Core/Include/core_cm55.h
- CMSIS/Core/Include/pmu_armv8.h
Changed ARM_PMU_Get_EVCNTR() function to mask top 16 bits of result so it's guaranteed to work across any Armv8.1-M implementation (not just Cortex-M55)
Fixed macro four definitions in core_cm55.h and core_armv81mml.h:
- PMU_EVCNTR_CNT_Msk
- PMU_EVTYPER_EVENTTOCNT_Msk
- PMU_TYPE_NUM_CNTS_Msk
- PMU_TYPE_SIZE_CNTS_Msk
Added macro definitions for the PMU Authentication Status Register.
Changed the dates at the top of each file.
> Macro fixes, New macro definitions, ARM_PMU_Get_EVCNTR() update

- CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8.c
This makes the `arm_math.h` include consistent with the rest of the files in CMSIS-NN, where `#include "arm_math.h` is used instead of `#include <arm_math.h>`.
> arm_max_pool_s8.c: use quotes instead of <> for arm_math.h include

- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
This fixes the way batches are handled in arm_convolve_s8.c used by TF Lite Micro.
See also https://github.com/ARM-software/CMSIS_5/pull/708#discussion_r417083087
> CMSIS-NN: Fix batch dimension in arm_convolve_s8

- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mult_q15.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mult_q7.c
Fixes #896.
I have not tested this directly. Let me know if a unit test is needed (I see some examples/instructions in the [UnitTest](https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS/NN/Tests/UnitTest) directory that I could follow). I've tested it indirectly through an example in the issue:
```C
#include <stdio.h>
int main() {
int x = -32;
printf("%d\n", (x >> 1));  // arithmetic shift
printf("%d\n", (((int) x + 0u) >> 1));  // logical shift (becomes unsigned before shift)
printf("%d\n", ((int) (x + 0u) >> 1));  // arithmetic shift (cast back to signed before shift)
return 0;
}
```
Using `gcc` (version 7.5.0) this outputs:
```
-16
2147483632
-16
```
The middle line corresponds to the old code. The last line corresponds to the updated code. 
One question:
1. (see commit in PR) …
> CMSIS-NN: Use arithmetic shifting in arm_nn_mult

- CMSIS/NN/Include/arm_nnsupportfunctions.h
Warnings related to sign conversions are looked at
and typecasted.
> CMSIS-NN: Fix warning in arm_nnsupportfunctions.h

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/README.md
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_wrapper_s8.c
The following functions have been ported to use the new API interface:
- arm_convolve_1_x_n_s8
- arm_convolve_1x1_s8_fast
- arm_convolve_s8
A wrapper function has been also created to make the integration of
those functions easier
> CMSIS-NN: Adopted the new API interface in convolution functions

- CMSIS/DSP/Include/arm_math.h
The float suffix replaces the need for a float cast in arm_clarke_f32.
This change is necessary to avoid large amount of warnings by arm_math.h when the -Wunsuffixed-float-constants flag is used. And using this compile flag is very reasonable on a processor with 32bit FPU.
> Fix - arm_math.h: Use the float suffix in arm_clarke_f32

- CMSIS/DSP/Source/BasicMathFunctions/arm_add_q7.c
- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ActivationFunctions/arm_relu_q7.c
- CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_u8_basic_ver1.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_depthwise_conv_s8_core.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_accumulate_q7_to_q15.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_add_q7.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_no_shift.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_no_shift.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_with_offset.c
- CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
- CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_u8.c
1. Doxygen warnings are fixed
2. Sign conversion warnings(-Wsign-conversion) and -Wextra warnings
are fixed for TFLu compliant MVE APIs
> CMSIS-NN: Fix warnings

- CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_q7.c
To avoid accuracy issues caused by earlier commits ede5bd3e2 and
cebb96c3f, the changes are reverted.
> CMSIS-NN : Revert update to arm_softmax_q7()

- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_basic.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast.c
Parts of the legacy APIs for non-DSP extension
Cortex-M CPUs have uint16 or signed chars for some
loop related variables. They are chagned to int.
Note: This does not affect TFLu compatible APIs
> CMSIS-NN: Use int for loop variables

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c
NULL check is done for optional bias parameter
> CMSIS-NN: Add bias null check for convolution functions

- CMSIS/DoxyGen/Pack/src/devices_schema.txt
Clarified usage of deprecated id and replacing name attributes.
Added missing init and uninit attributes.
> Doxygen: Enhanced Pack documentation about device memory specification.

- CMSIS/DSP/Source/FastMathFunctions/arm_cos_f32.c
- CMSIS/DSP/Source/FastMathFunctions/arm_sin_f32.c
The size of the sinTable is 512 + 1 according to FAST_MATH_TABLE_SIZE = 512. The documentation says that sin(cos) is derived by linear interpolation with a value of 256, so I've corrected this to 512.
> Correct DSP document: Correct the size of the referenced sine table.

- CMSIS/DSP/Examples/ARM/arm_bayes_example/arm_bayes_example_f32.c
Closes #1001
**arm_gaussian_naive_bayes_predict_f32** already returned index, modified the example to remove the redundant expressions.
> CMSIS-DSP: Modified the arm_bayes_example

- CMSIS/DSP/Source/DistanceFunctions/arm_rogerstanimoto_distance.c
Corrected the names of people based on the paper.
(https://science.sciencemag.org/content/132/3434/1115)
Roger Stanimoto -> Rogers Tanimoto
> Correct DSP Documents: Correct the names of people.

- CMSIS/DoxyGen/Core/src/Ref_NVIC.txt
there was fault for `uint32_t NVIC_GetEnableIRQ(IRQn_Type IRQn)` function documentation that fixed.
> fix bug in documentation

- CMSIS/Core/Include/cmsis_gcc.h
asm keyword is replaced by compiler specific  __ASM define
for __SXTB16_RORn()
> CMSIS-Core: Fix for correct use of asm keyword

- CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.c
Closes #1023 
FIR documentation has incorrectly described about **pState** because there is no new inputs and the values in the **pState** are circulated.
```c
//x[n-numTaps+1], x[n-numTaps], x[n-numTaps-1], x[n-numTaps-2]... .x[0], x[1], ... , x[blockSize-1]}
```
Therefore I fixed it.
```c
//{x[n-numTaps+1], x[n-numTaps], x[n-numTaps-1], x[n-numTaps-2]....x[n](==pSrc[0]), x[n+1](==pSrc[1]), ..., x[n+blockSize-1](==pSrc[blockSize-1])}
```
> CMSIS-DSP: Fix FIR document

- CMSIS/DSP/Source/TransformFunctions/CMakeLists.txt
to not build float16 code if the datatype is disabled.
Not sure if the condition should be extended. Feel free to adapt
> Do not build f16 code if datatype is disabled

- CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c
- CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c
- CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c
- CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c
- CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c
There is a small typo in CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c, CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.c, CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.c, CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c, CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c, CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c, CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c, CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c, CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c.
Should read `accumulate` rather than `accumlate`.
> docs: fix simple typo, accumlate -> accumulate

- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_1x_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_4x_s8.c
Replaced __asm keyword with __ASM for a couple of functions
arm_nn_mat_mul_core_1x_s8.c & arm_nn_mat_mul_core_4x_s8.c
> Replace keyword __asm with __ASM

- CMSIS/NN/.clang-format
.clang-format file is added to NN directory to
specify modifications to the default style when
using clang-format
> CMSIS-NN: Add .clang-format file

- CMSIS/DSP/Source/BasicMathFunctions/arm_and_u16.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_and_u32.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_and_u8.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_not_u16.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_not_u32.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_not_u8.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_or_u16.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_or_u32.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_or_u8.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u16.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u32.c
- CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u8.c
Compile error about the unsigned / signed integer :
CMSIS_5/CMSIS/DSP/Source/BasicMathFunctions/arm_and_u8.c:66:19: error: incompatible types when assigning to type 'q7x16_t' {aka 'int8x16_t'} from type 'uint8x16_t'
66 | vecSrcA = vld1q(pSrcA);
CMSIS_5/CMSIS/DSP/Source/BasicMathFunctions/arm_and_u8.c:67:19: error: incompatible types when assigning to type 'q7x16_t' {aka 'int8x16_t'} from type 'uint8x16_t'
67 | vecSrcB = vld1q(pSrcB);
CMSIS_5/CMSIS/DSP/Source/BasicMathFunctions/arm_and_u8.c:69:30: error: incompatible type for argument 1 of '__arm_vandq_u8'
69 | vst1q(pDst, vandq_u8(vecSrcA, vecSrcB) );
> CMSIS-DSP: Fix signed/unsigned integer data type issue

- CMSIS/DSP/ComputeLibrary/Include/NEMath.h
This brings vtaylor_polyq_f16 in line with vtaylor_polyq_f32, which is already loading the data as expected.
> CMSIS-DSP: Correct loading of FP16 data.

- CMSIS/NN/Tests/UnitTest/CMakeLists.txt
- CMSIS/NN/Tests/UnitTest/README.md
Make it possible to build all unit tests with one target.
> CMSIS-NN: Add custom target for unit tests

- CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_HWC_q7_fast_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_basic.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15_reordered.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q7.c
Mostly related to unused parameter with one
in elementwise op related to sign conversion.
> CMSIS-NN : Fix compiler warnings

- CMSIS/DoxyGen/Pack/src/pdsc_format.txt
- CMSIS/DoxyGen/SVD/src/svd_schema.txt
- CMSIS/DoxyGen/Zone/src/XML_Format.txt
SVD:
- xmlns:xs has type xs:string, not xs:decimal
- xs:noNamespaceSchemaLocation was missing in favor
of repeated xmlns:ns attribute.
PDSC:
- xmlns:xs has type xs:string, not xs:decimal
Zone:
- xmlns:xs has type xs:string, not xs:decimal
> Doxygen: Fixed XML schema documentation (issue #1044)

- CMSIS/DoxyGen/Core/src/Ref_PMU8.txt
Add some notes to remind users to enable trace via:
CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
before using PMU.
This is originally mentioned in
'Application Note
Armv8.1-M Performance Monitoring User Guide'
> DoxyGen: remind users to enable trace before using PMU

- CMSIS/DoxyGen/Pack/src/config_wizard.txt
Extends the configuration wizard annotation language to support
* key identifiers on other options than `<o>`
* negative integers in option range modifiers
* default values for GUI "reset to default" functionality
* format specifiers for GUI display
* array type
> ConfigWizard: Extend annotation syntax

- CMSIS/RTOS2/RTX/Source/rtx_lib.c
Call osKernelInitialize() from IAR startup hook similar to
ARMCLANG and GNUARM.
> RTX5: Add os initialization for IAR

- CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f16.c
- CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.c
- CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.c
- CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.c
- CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.c
This attempts to ensures that even on a 64bit system, the array access
will be treated as a negative number, not a large unsigned offset ending
up reading from the middle of nowhere.
> CMSIS-DSP: Ensure correlation array index is signed.

- CMSIS/NN/CMakeLists.txt
- CMSIS/NN/Source/ActivationFunctions/CMakeLists.txt
- CMSIS/NN/Source/BasicMathFunctions/CMakeLists.txt
- CMSIS/NN/Source/CMakeLists.txt
- CMSIS/NN/Source/ConcatenationFunctions/CMakeLists.txt
- CMSIS/NN/Source/ConvolutionFunctions/CMakeLists.txt
- CMSIS/NN/Source/FullyConnectedFunctions/CMakeLists.txt
- CMSIS/NN/Source/NNSupportFunctions/CMakeLists.txt
- CMSIS/NN/Source/PoolingFunctions/CMakeLists.txt
- CMSIS/NN/Source/ReshapeFunctions/CMakeLists.txt
- CMSIS/NN/Source/SVDFunctions/CMakeLists.txt
- CMSIS/NN/Source/SoftmaxFunctions/CMakeLists.txt
- CMSIS/NN/Tests/UnitTest/CMakeLists.txt
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_avgpool_s8/CMakeLists.txt
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_convolve_1x1_s8_fast/CMakeLists.txt
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_convolve_s8/CMakeLists.txt
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_3x3_s8/CMakeLists.txt
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8/CMakeLists.txt
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8_opt/CMakeLists.txt
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_max_pool_s8/CMakeLists.txt
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_softmax_s8/CMakeLists.txt
* Builds CMSIS-NN source the same way as when building unit tests and
when building it standalone.
* Builds SVDF as well.
> CMSIS-NN: Refactor CMake

- CMSIS/Core/Include/cachel1_armv7.h
The addr argument needs to accept volatile void* in order
to be generic. In fact it doesn't affect the function
behavior which actual data type is used as only the
address of the data is required.
> CMSIS-Core(M): Fix cache maintenance functions.

- CMSIS/CoreValidation/Tests/ac5.rtebuild
- CMSIS/CoreValidation/Tests/build.py
- CMSIS/CoreValidation/Tests/config/core_a/rtebuild.sct
- CMSIS/CoreValidation/Tests/main.c
- Add missing scatter file for Arm Compiler 6
- Add map file generation with Arm Compiler 5
- Remove filter from build.py
- Fix main.c handler function definitions
> CoreValidation: Fix Cortex-A builds.

- ARM.CMSIS.pdsc
History is updated to show that SVDF is
optimized for Helium tech as well.
> CMSIS-NN : Update history in pdsc file

- CMSIS/CoreValidation/Tests/config/core_a/rtebuild.sct
The compiler issues warning about unsupported (deprecated)
target architectures when called with specific -march.
> CoreValidation: Fix Arm Compiler 6 linker warnings.

- CMSIS/DoxyGen/Core/src/Ref_cm4_simd.txt
SIMD is not only supported on M4/M7 (Armv7E-M) but also on
Armv8-MML and Armv8.1-M.
> Doxygen: Fix support statement for SIMD instructions.

- CMSIS/DoxyGen/DAP/src/dap_USB_cmds.txt
These changes implement the proposal from #962, improving the version info reported by the DAP_Info command.
- Add ID 0x07, `DAP_ID_PRODUCT_VER`: **Product Firmware Version** (string), vendor-specified version format.
- A stub for `DAP_ProductFirmwareVerString()` was added to `DAP_config.h`.
- Change ID 0x04 to be specified as: **CMSIS-DAP Protocol Version** (string). The value must be one of the versions from the \ref dap_revisionHistory "CMSIS-DAP revision history", such as "2.0.0"
- Changed the constant in `DAP.h` to `DAP_ID_CMSIS_DAP_VER`.
- Kept `DAP_ID_FW_VER` as an alias of `DAP_ID_CMSIS_DAP_VER`, with a comment saying it's deprecated.
Other included changes:
- Rebuilt the example projects to update the included .axf files.
- Added a `.gitignore` to ignore the generated `Objects` …
> CMSIS-DAP: DAP_Info documentation clarifications

- CMSIS/RTOS2/RTX/Include/rtx_def.h
Using the same license as any other file in RTX. 
I found this while working with 5.8.0 release (our license check in Mbed OS failed due to non permissive license found). It would be good to have license check introduced to gate PRs.
> rtx-def: fix license - apache 2.0

- CMSIS/Core/Include/core_armv81mml.h
- CMSIS/Core/Include/core_cm55.h
This fixes inconsistencies between the documentation available [here](https://developer.arm.com/documentation/101051/0100/Performance-Monitoring-Unit-Extension/PMU-register-summary) and the definition of `PMU_Type`.
> Fix PMU_Type spurious reserved register and offset documentation.

- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ActivationFunctions/arm_relu_q15.c
- CMSIS/NN/Source/ActivationFunctions/arm_relu_q7.c
- CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c
- CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_HWC_q7_fast_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_basic.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast_nonsquare.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_mat_q7_vec_q15.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_mat_q7_vec_q15_opt.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q15.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q15_opt.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q7.c
- CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q7_opt.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_accumulate_q7_to_q15.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_add_q7.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mult_q15.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mult_q7.c
- CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_no_shift.c
- CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8.c
- CMSIS/NN/Source/PoolingFunctions/arm_pool_q7_HWC.c
- CMSIS/NN/Tests/UnitTest/CMakeLists.txt
Left over CMSIS-DSP dependencies are removed
For functions with just DSP extension optimization,
the reference C implementation(if available) is picked
for processors with Helium Technology as auto vectorization
can potentially give a better performance. This affects only
the non-TFLM functions.
> CMSIS-NN: Cleanup of CMSIS-DSP dependencies

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast.c
Input constraint is updated as per  #1168 to support only
output dimension that is even.
> CMSIS-NN: Update input constraint for arm_convolve_HWC_q15_fast

- CMSIS/NN/Include/arm_nn_math_types.h
- CMSIS/NN/Include/arm_nn_tables.h
- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_svdf_s8.c
- CMSIS/NN/Source/SVDFunctions/arm_svdf_s8.c
- CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_s8.c
All dependencies to CMSIS-DSP except for the return
type are removed.
> CMSIS-NN: Remove depdendency to CMSIS-DSP

- CMSIS/DSP/Source/ComplexMathFunctions/CMakeLists.txt
Without these changes I would get the following error when compiling my CMake project with `cmake .. -DCONFIGTABLE=ON -DRFFT_Q15_256=ON -DARM_COS_F32=ON`:
```
CMake Error at lib/CMSIS_5/CMSIS/DSP/Source/interpol.cmake:4 (target_compile_definitions):
Cannot specify compile definitions for target "CMSISDSPFastMath" which is
not built by this project.
Call Stack (most recent call first):
lib/CMSIS_5/CMSIS/DSP/Source/ComplexMathFunctions/CMakeLists.txt:15 (interpol)
```
I believe `CMSIS/DSP/Source/ComplexMathFunctions/CMakeLists.txt` is using `interpol(CMSISDSPFastMath)` by mistake when it should be using `interpol(CMSISDSPComplexMath)` instead.
@christophe0606 what do you think?
> CMSIS-DSP: Correct interpol(...) arg in ComplexMathFunctions CMakeLists.txt

- CMSIS/DoxyGen/Core/src/core_cm7.txt
In c0e1824 the data type of the addr parameters were changed
to volatile void* but the documentation got missed.
> DoxyGen: Fixed documentation of cache maintenance functions.

- CMSIS/NN/README.md
- CMSIS/NN/Tests/UnitTest/CMakeLists.txt
Adding -Ofast (and -fomit-frame-pointer for clarity) to unit tests.
> CMSIS-NN: Add -Ofast to unit tests and update README

- CMSIS/DoxyGen/Pack/src/sdf_schema.txt
Added SDF format description updates for ADIv6 support.
Added ARMV81MML and Cortex-M55 CPUs.
> ADIv6 extensions for SDF format

- CMSIS/DSP/Include/arm_math_types.h
- CMSIS/DSP/Include/arm_math_types_f16.h
- CMSIS/DSP/PrivateInclude/arm_vec_fft.h
- CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_f16.c
- CMSIS/DSP/Source/TransformFunctions/arm_cfft_q15.c
- CMSIS/DSP/Source/TransformFunctions/arm_cfft_q31.c
- CMSIS/DSP/Source/TransformFunctions/arm_rfft_q15.c
- CMSIS/DSP/Source/TransformFunctions/arm_rfft_q31.c
Cleaned out some non-standard C code, typeof() and using
"const" variables as constants.
Also added some initial IAR support.
> DSP: Eliminate some non-standard C code

- CMSIS/DSP/PrivateInclude/arm_vec_fft.h
- CMSIS/DSP/Source/FastMathFunctions/arm_vlog_f16.c
- CMSIS/DSP/Source/FastMathFunctions/arm_vlog_q15.c
- CMSIS/DSP/Source/FastMathFunctions/arm_vlog_q31.c
- CMSIS/DSP/Source/MatrixFunctions/arm_mat_ldlt_f32.c
- CMSIS/DSP/Source/SupportFunctions/arm_q15_to_float.c
- CMSIS/DSP/Source/SupportFunctions/arm_q7_to_float.c
- CMSIS/DSP/Source/TransformFunctions/arm_cfft_q15.c
The IAR compiler appears to provide more warnings about type
mismatches than the other compilers. This cleans a lot of them up.
Also cleaned out some trailing white space in the updated files.
> DSP: Cleanup of type mismatches

- CMSIS/DSP/Include/arm_math_types.h
Hello,
One more step to support Apple C Compiler: we need to add a specific ignore warning related to old c cast style.
Thanks again!
> Ignore old c cast style not supported by apple cc

- CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_f32.c
- CMSIS/DSP/Source/MatrixFunctions/arm_mat_cholesky_f32.c
Hello all,
Please find here a fix for a warning happening in arm64 where a tmp variable is defined but not used.
Thanks again!
> Fix warning unused tmp variable

- CMSIS/NN/CMakeLists.txt
- CMSIS/NN/Source/ActivationFunctions/CMakeLists.txt
- CMSIS/NN/Source/BasicMathFunctions/CMakeLists.txt
- CMSIS/NN/Source/CMakeLists.txt
- CMSIS/NN/Source/ConcatenationFunctions/CMakeLists.txt
- CMSIS/NN/Source/ConvolutionFunctions/CMakeLists.txt
- CMSIS/NN/Source/FullyConnectedFunctions/CMakeLists.txt
- CMSIS/NN/Source/NNSupportFunctions/CMakeLists.txt
- CMSIS/NN/Source/PoolingFunctions/CMakeLists.txt
- CMSIS/NN/Source/ReshapeFunctions/CMakeLists.txt
- CMSIS/NN/Source/SVDFunctions/CMakeLists.txt
- CMSIS/NN/Source/SoftmaxFunctions/CMakeLists.txt
Sources added to the cmsis-nn static library should with added with
scope PRIVATE. Else they will be exported and built by the other
target linking the library.
Compile options should be set per target.
Change-Id: Ib5c5ce1db8f7baa28bba411be7eea955f5a3af29
> CMSIS-NN: CMake updates

- CMSIS/NN/Source/SVDFunctions/arm_svdf_s8.c
The size argument to memmove reads one element out of bounds. This PR fixes that bug.
> Fix read-out-of-bounds bug in SVDF kernel

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Source/ConcatenationFunctions/arm_concatenation_s8_w.c
- CMSIS/NN/Source/ConcatenationFunctions/arm_concatenation_s8_x.c
- CMSIS/NN/Source/ConcatenationFunctions/arm_concatenation_s8_y.c
- CMSIS/NN/Source/ConcatenationFunctions/arm_concatenation_s8_z.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_fast_s16.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s16.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s8.c
- CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c
- CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8.c
- CMSIS/NN/Source/ReshapeFunctions/arm_reshape_s8.c
- CMSIS/NN/Source/SVDFunctions/arm_svdf_s8.c
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_3x3_s8/test_arm_depthwise_conv_3x3_s8.c
- CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8/test_arm_depthwise_conv_s8.c
This pull request
- adds NULL-checks for buffers
- checks for division by zero
- removes duplicated testcase
- fixes a bug in the arm_depthwise_conv_wrapper_s8() function
- adds dynamic allocation of context buffer in testcases
> CMSIS-NN: Coverity warning fixes

- CMSIS/NN/Include/arm_nnsupportfunctions.h
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
- CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
- CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_4x_s8.c
API arm_nn_mat_mul_core_4x_s8 is refactored to generate the
quantized output instead of MAC results.
Change-Id: Iacfed7811ebd4609540602f56ba03dd8ac219ee6
> CMSIS-NN: Refactor arm_nn_mat_mul_core_4x_s8 for MVE

- CMSIS/DSP/Include/arm_math_memory.h
This warnings are soved:
CMSIS/DSP/Include/arm_math_memory.h:144:21: warning: conversion from 'q31_t' {aka 'int'} to 'q15_t' {aka 'short int'} may change value [-Wconversion]
CMSIS/DSP/Include/arm_math_memory.h:145:28: warning: conversion from 'q31_t' {aka 'int'} to 'q15_t' {aka 'short int'} may change value [-Wconversion]
CMSIS/DSP/Include/arm_math_memory.h:166:17: warning: conversion from 'q31_t' {aka 'int'} to 'q15_t' {aka 'short int'} may change value [-Wconversion]
CMSIS/DSP/Include/arm_math_memory.h:167:17: warning: conversion from 'q31_t' {aka 'int'} to 'q15_t' {aka 'short int'} may change value [-Wconversion]
CMSIS/DSP/Include/arm_math_memory.h:227:19: warning: conversion from 'q31_t' {aka 'int'} to 'q7_t' {aka 'signed char'} may change value [-Wconversion] …
> This fixed some GCC warnings with -WConversion enabled:

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/README.md
Minor document update to explicitly mention
that it is for Cortex-M processors.
> CMSIS-NN: Update documentation

- CMSIS/NN/Include/arm_nnfunctions.h
- CMSIS/NN/Include/arm_nnsupportfunctions.h
Adds back arm_nn_mat_mult_kernel_q7_q15_reordered.
Fix for: https://github.com/ARM-software/CMSIS_5/issues/1432
> CMSIS-NN: Add back missing prototype

- CMSIS/DSP/Include/arm_math_types.h
Dear @christophe0606, 
The goal of this pull request is to fix a compilation issue encountered with Visual Studio 2022 if the Arm64EC mode is used.
For some reasons, including the <arm_neon.h> directly in Arm/Arm64 works, but not in Arm64EC. As a workaround it is possible to use <arm64_neon.h> instead in Arm64EC.
I don't know if there is a particular reason for Microsoft to do that (I have asked here: https://docs.microsoft.com/en-us/answers/questions/791892/why-is-it-not-working-to-include-arm-neonh-in-a-ar.html). This might also just be a bug on Microsoft side?
Meanwhile for CMSIS to support Visual Studio 2022 with Arm64EC, the following change is required.
Thanks in advance!
Best Regards,
JbR
> Fixing compilation issue with Visual Studio 2022 in Arm64EC

- CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
Avoid using strbq_scatter_offset_s32 if possible. This is the typical
case for fully connected.
> CMSIS-NN: Improve performance for armclang 6.18

- CMSIS/Core/Include/cachel1_armv7.h
More details, see https://github.com/ARM-software/CMSIS_5/issues/620
The issue only happens when local variables are in stack (GCC O0). If local variables are saved
in general purpose register, then the function is OK.
When local variables are in stack, after disabling the cache, flush the local variables cache
line for data consistency.
> Fix the endless loop issue with GCC O0.
